### ISSUE TITLE
Retire `JavaScript 1.7` in the JS picker

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsfiddle/jsfiddle-users#1861]
Retire `JavaScript 1.7` as all of its features are no longer edge.

All previously created fiddles should be switched to JS.

**Comment by chrisjj** [comment]
> all of its features are no longer edge.

Why is that grounds for retirement?

**Comment by chrisjj** [comment]
Perhaps you meant obsolescent. This is not grounds for retirement.

**Comment by chrisjj** [comment]
Perhaps the reason to remove it is no-one is likely to use it e.g. indicated by no-one having used it for a long time.

**Comment by nmecodes** [comment]
Well, I think it is a good decision to upgrade JS 1.7 to being the default, as I, a little annoyingly, have to choose it all the time to use what are now pretty commonplace features.  Leaving it in as an option would be confusing; thus, retirement of the option, at least in the dropdown menu, is a good idea.

**Comment by oskarkrawczyk** [comment]
`JavaScript 1.7` is now hidden, all previously created fiddles using this language will still be available (users will be able to work on them and update them)
