### ISSUE TITLE
/show page not working?

### ISSUE THREAD

**Issue by NathanWailes** [jsfiddle/jsfiddle-users#1864]
I have the following jsFiddle: https://jsfiddle.net/nathanwailes/ot8ajezs/189/

For the past ~6 months I had been able to go to https://jsfiddle.net/nathanwailes/ot8ajezs/189/show to see the code running by itself, without any of jsFiddle's UI.

It's now not working; was the `/show` page feature removed?

This is what I see now:

![image](https://github.com/jsfiddle/jsfiddle-users/assets/1755791/2c56ddad-b38e-42d8-890b-7ba058f9c6e4)

**Comment by pawelfus** [comment]
+1 for this
Really helpful when debugging on mobile. Any suggestions for a workaround for my use case? Thanks!

**Comment by oskarkrawczyk** [comment]
@pawelfus I think the best way is to follow the solution provided in my comment above.

**Comment by gaby-de-wilde** [comment]
Maybe make it available only to the author of the fiddle?

**Comment by oskarkrawczyk** [comment]
@gaby-de-wilde that's an awesome idea!

Will do it this week.

**Comment by oskarkrawczyk** [comment]
`/show` now works again but for logged in users only - not only the author of the fiddle but any logged in users.

@gaby-de-wilde again, thanks for the idea.
