### ISSUE TITLE
Why github integration not working for me?

### ISSUE THREAD

**Issue by Neet-Nestor** [jsfiddle/jsfiddle-users#1867]
Following this instruction: https://docs.jsfiddle.net/github-integration/untitled-1

I have this repo path with the files:
https://github.com/Neet-Nestor/web-llm/tree/main/examples/jsfiddle/simple-chat

And I used the following link to create jsfiddle:
https://jsfiddle.net/gh/get/library/pure/Neet-Nestor/web-llm/tree/main/examples/jsfiddle/simple-chat

But it shows me the following 404 error:
> Repository/Gist not found: https://api.github.com/repos/Neet-Nestor/web-llm/contents/examples/jsfiddle/simple-chat

While actually the API gives correct response:
https://api.github.com/repos/Neet-Nestor/web-llm/contents/examples/jsfiddle/simple-chat

What's wrong with this?

**Comment by oskarkrawczyk** [comment]
> While actually the API gives correct response:
> https://api.github.com/repos/Neet-Nestor/web-llm/contents/examples/jsfiddle/simple-chat

Maybe there's a problem with GH, none of the links you've provided work for me.

![Screenshot 2024-05-30 at 18 23 52](https://github.com/jsfiddle/jsfiddle-users/assets/34213/27416064-4cde-4567-b8b2-e441cdd65033)

![Screenshot 2024-05-30 at 18 25 35](https://github.com/jsfiddle/jsfiddle-users/assets/34213/f3beb64f-2ae1-42ed-817f-22c99ed1bd49)

**Comment by Neet-Nestor** [comment]
@oskarkrawczyk 
Sorry that's because I deleted the repo I used for testing there. Please try the following. The problem persists for me.

I created a repo with the example files here:
https://github.com/Neet-Nestor/jsfiddle

The link works:
https://api.github.com/repos/Neet-Nestor/jsfiddle/contents

But this doesn't:
https://jsfiddle.net/gh/get/library/pure/Neet-Nestor/jsfiddle/contents

<img width="697" alt="Screenshot 2024-05-30 at 4 54 58 PM" src="https://github.com/jsfiddle/jsfiddle-users/assets/23090573/89cdcee4-6b0d-4669-9171-c87e480b99df">
