### ISSUE TITLE
New user registration is broken

### ISSUE THREAD

**Issue by chriskkim** [jsfiddle/jsfiddle-users#1869]
# Issue

The signup mechanism seems to be broken at https://jsfiddle.net/user/signup/. This 500 error doesn't seem to be browser-dependent.

# Screenshots

<img width="496" alt="Screenshot 2024-07-03 at 11 51 20 PM" src="https://github.com/jsfiddle/jsfiddle-users/assets/23746948/f31c8bdd-013f-4984-a24a-71622c744564">
<img width="284" alt="Screenshot 2024-07-03 at 11 51 22 PM" src="https://github.com/jsfiddle/jsfiddle-users/assets/23746948/a109e05f-6c26-40e5-ae95-8e7fb4027577">

**Comment by oskarkrawczyk** [comment]
Thanks for letting me know – fix is deploying as I write this.
