### ISSUE TITLE
Tidy breaks all conditional chaining and nullish coalescing operators. 

### ISSUE THREAD

**Issue by mplungjan** [jsfiddle/jsfiddle-users#1870]
If I press tidy, jsFiddle breaks all conditional chaining and nullish coalescing operators. 
If I change to JS1.7 as suggested in (https://github.com/jsfiddle/jsfiddle-users/issues/1771) I just do not get the error shown, but the script is still broken.

?.
??
??=
&&=
||=

Valid JS

<img width="298" alt="image" src="https://github.com/jsfiddle/jsfiddle-users/assets/1433276/cb448421-c4f6-42cf-ac53-7c58c9117194">

Clicking **Tidy** breaks it

<img width="297" alt="image" src="https://github.com/jsfiddle/jsfiddle-users/assets/1433276/8336d232-f2fc-46dc-a704-cd143d0b8087">

Using JS 1.7 hides the error

<img width="238" alt="image" src="https://github.com/jsfiddle/jsfiddle-users/assets/1433276/5337566b-7095-4a6d-9be4-560824fe9626">

**Comment by oskarkrawczyk** [comment]
Refactored the way tidy works, from what I can see this issue is no more.

**Comment by mplungjan** [comment]
Where can I test?
This one I just made still shows the issue
https://jsfiddle.net/mplungjan/7ergahun/

**Comment by oskarkrawczyk** [comment]
Perhaps a caching issue - I've additionally purged cache on CloudFlare, perhaps this will help.

**Comment by mplungjan** [comment]
Ok, that worked - however I get a parsing error on the otherwise correct ??=

https://jsfiddle.net/mplungjan/Lp2v1gcz/

let a = x?.y;
let b = 0 ?? 42;
let z ??= [];  // parsing error 
let c &&= 2;
let d ||= 3;

**Comment by oskarkrawczyk** [comment]
Not much I can do about that since it's a browser thing. Safari and Firefox will throw a `SyntaxError`

![Screenshot 2024-09-19 at 11 25 36](https://github.com/user-attachments/assets/489bbc9e-8dd9-49cc-8e9d-0125b29ef587)

![Screenshot 2024-09-19 at 11 27 25](https://github.com/user-attachments/assets/43db55d8-b288-48aa-b0a5-b864321afa45)
