### ISSUE TITLE
Allow "speaker-selection" permission policy in iframes

### ISSUE THREAD

**Issue by jan-ivar** [jsfiddle/jsfiddle-users#1872]
I use JS fiddles for code examples in my blog posts. But for my [most recent post](https://blog.mozilla.org/webrtc/how-webrtc-speaker-selection-works/) I couldn't, because jsfiddle.net does not delegate the allow=["speaker-selection"](https://w3c.github.io/mediacapture-output/#permissions-policy-integration) permission policy.

STR in Firefox:
1. Open https://jsfiddle.net/jib1/19yjpemr/ and click the `Default speakers...` button.

Expected result: A Firefox speakers picker
Actual result: `NotAllowedError: Document's Permissions Policy does not allow selectAudioOutput()`

Suggested fix:
```diff
- <iframe name="result" allow="midi; geolocation; microphone; camera; display-capture; ..."
+ <iframe name="result" allow="midi; geolocation; microphone; camera; display-capture; speaker-selection; ..."
```

Other browsers do not support this yet, so you can feature detect to avoid log-spam if that is a concern. This should do it:
```js
if ("selectAudioOutput" in navigator.mediaDevices) { ... }
```

**Comment by oskarkrawczyk** [comment]
Done
