### ISSUE TITLE
JSFiddle sites are very slow to load

### ISSUE THREAD

**Issue by yorkmoy** [jsfiddle/jsfiddle-users#1873]
JSFiddle sites have become very slow to load. Our site monitors began failing at 5:07 pm ET. Thank you for looking into this!

Confirmed affected sites:
https://jsfiddle.net/
https://jsfiddle.net/user/chartiq/fiddles/

**Comment by oskarkrawczyk** [comment]
We're experiencing tech issues at the moment. Trying to solve them asap.

**Comment by yorkmoy** [comment]
@oskarkrawczyk Our fiddles are loading normally now. Our monitors show normal responses resuming at 2:37 am RT. I am closing this this issue. Thank you for responding!
