### ISSUE TITLE
Mechanism to automatically verify existence of a fiddle?

### ISSUE THREAD

**Issue by dead-claudia** [jsfiddle/jsfiddle-users#1876]
We have a broken link checker in our GitHub Actions workflow, and [it's returning 403s now](https://github.com/MithrilJS/mithril.js/actions/runs/10138835139/job/28056897805?pr=2897#step:5:24). How should we work around it?

I tried a bare request without headers, and that seems to return something.

And to be clear, [this is what generated that](https://github.com/MithrilJS/mithril.js/blob/97666754f6154fc32538975440f80c529327a434/scripts/lint-docs.js#L48-L91).

If it's anti-spam (as I suspect), I'd be okay with adding an API token header and/or retargeting it if needed. If that's the case, please tell me how/where I can get that, so we can unbreak our CI.

**Comment by oskarkrawczyk** [comment]
My bet is CloudFlare detects this request as suspicious and blocks it.

It this being made from a specific host/ip?

**Comment by dead-claudia** [comment]
@oskarkrawczyk It's from a GitHub-hosted runner, so I don't know.

**Comment by dead-claudia** [comment]
Okay, appears to probably be a flake caused by triggering anti-bot protections. I tried it with a concurrency-limited requestor and some extra headers, and that seems to work. So, I'm closing this.
