### ISSUE TITLE
CSS style override

### ISSUE THREAD

**Issue by bramvandijk88** [jsfiddle/jsfiddle-users#1877]
I've been using your services for 2 years now, but the JSfiddle update broke something for me. The CSS on my pages seems hard-coded to have all fonts set to white. I confirmed that this issue only happens in the new JSfiddle, and is not happening in my private javascript pages. 

For example, the following page used to have black fonts and white tick boxes:

https://jsfiddle.net/bramvandijk88/v5oa4hkz/8/

As you can see, all the fonts are white in this fiddle, even though I specified nothing about the fonts. I can add an overwrite in the CSS:

* {
  color: black;
}

Which fixes it, but it also makes the tick boxes black (essentially because I set everything... black). I suspect it has something to do with the "Results pane Following the Theme" thing that is shown in your patch notes. 

Would appreciate a fix for this, thanks for everything you do! :)

**Comment by oskarkrawczyk** [comment]
I brought the old behavior back, the results panel will now be styled as in the previous version.

**Comment by bramvandijk88** [comment]
Thank you so much for how quickly you fixed this! Looking forward to see what your secret plans are with 3.0! ❤️
