### ISSUE TITLE
Code snippets don't work after the update

### ISSUE THREAD

**Issue by adrianszymanski89** [jsfiddle/jsfiddle-users#1880]
Hi

We noticed that all of the examples in our documentation handled by jsFiddle only work if we open them and log in to our account. 

After the initial investigation, one of our suspicions was that it would happen if the OS language were not set to English. It's also set as the default on our jsFiddle account, but it didn't make any difference for some people on our team.

Then we noticed that there is an additional request that is probably causing this issue:

![image](https://github.com/user-attachments/assets/1431332b-0f45-44df-96d4-86c328c02c5c)

And here's the error we get after we try to run any of our code examples:

![image](https://github.com/user-attachments/assets/63fd3179-9d0f-4904-b97c-62bdca4a79e5)

**Comment by oskarkrawczyk** [comment]
@adrianszymanski89 the latter part of the request URL seems like gibberish.

Can you provide a URL to the docs that contains a JSFiddle link? I'd like to check this myself.

**Comment by oskarkrawczyk** [comment]
Ok, I found the links in your docs but I cannot see anything misbehaving.

> only work if we open them and log in to our account.

Can you elaborate on this? I'm logged out and see the examples working. What happends when they "don't work" on your end?

I need more details, since I don't know what I'm looking for.

**Comment by adrianszymanski89** [comment]
Hi @oskarkrawczyk 

Sure. So, if I try to open any of the examples and I'm not logged in to our account, that's what I see:

<img width="1343" alt="image" src="https://github.com/user-attachments/assets/a9266060-e1b1-4604-ac9f-b798bfffa567">

When I try to press the "Uruchom" button, it shows the error I mentioned. Additionally, if I want to click on any other option, let's say tabs placement, that's what I get:

<img width="387" alt="image" src="https://github.com/user-attachments/assets/b64b90b8-6596-413d-bc57-18b11f5e3a3b">

My environment:

Google Chrome 128 / macOS Sonoma 14.5

**Comment by oskarkrawczyk** [comment]
Ok thanks, do you see any JS errors in the console? Or maybe you use content blockers?

It sure does look like part of the editor JS didn't load at all.

**Comment by oskarkrawczyk** [comment]
Alright I can see the problem, indeed a JS error. Thanks for pointing it out. I'll fix this soon.

**Comment by adrianszymanski89** [comment]
@oskarkrawczyk 

No ad blockers on my side. Here's the console log:

![image](https://github.com/user-attachments/assets/f7357f09-4c5a-45e5-8986-0afb0058cf3f)

**Comment by oskarkrawczyk** [comment]
@adrianszymanski89 A fix is being deployed as I write this. Thanks for letting me know about this one - an exceptionally weird bug caused by UI translation strings.

**Comment by adrianszymanski89** [comment]
@oskarkrawczyk 

Much appreciated! I can confirm that it's fixed. Thanks!
