### ISSUE TITLE
aspect-ratio is not a valid css prop?

### ISSUE THREAD

**Issue by notchris** [jsfiddle/jsfiddle-users#1881]
![image](https://github.com/user-attachments/assets/106de17c-6c61-41b2-b017-f97e9daed8b0)

https://jsfiddle.net/notchris/bvqy9fda/

Is this a bug?

**Comment by oskarkrawczyk** [comment]
The 3rd party CSS linter is somehow outdated and has no notion of newer CSS properties. You can ignore this, doesn't affect how the fiddle is being rendered.

I already have an issue opened for updating the linter so closing this one.

**Comment by notchris** [comment]
@oskarkrawczyk Sounds good, How difficult is it to update the linter?

**Comment by oskarkrawczyk** [comment]
@notchris Pretty difficult since it's not a matter of updating but a matter of integrating a different one.
