### ISSUE TITLE
The new UI does not improve accessibility

### ISSUE THREAD

**Issue by notchris** [jsfiddle/jsfiddle-users#1882]
The new jsfiddle design does not improve usability / accessibility. 

![image](https://github.com/user-attachments/assets/3fe53302-9bac-4e59-9809-aa877b448484)

The user account link (previously top right), is now only available in the bottom left which is not super visible and does not have an alt tag with information about the click action. In addition the new user thumb added in the left / center has no click action.

![image](https://github.com/user-attachments/assets/7cf46317-b34b-46d7-b73c-007e0a332781)

I am happy to provide more examples, but respectfully, this is a step backwards.

**Comment by oskarkrawczyk** [comment]
@notchris Sure, provide more, I'm happy to consider improvements on the 3.0 update.

**Comment by oskarkrawczyk** [comment]
Haven't heard back, closing for now.
