### ISSUE TITLE
Suggestion dropdown is overlaps with background content (Z-index issue) 

### ISSUE THREAD

**Issue by coolpinkzz** [jsfiddle/jsfiddle-users#1886]
Description:

In JSFiddle's CSS and code editor sections, when typing in code, an autocomplete suggestion dropdown appears. This dropdown overlaps with the background content, making the suggestions either invisible or distorted. This affects visibility and usability of the dropdown content, making it difficult to select suggestions.

Environment:

Platform: JSFiddle (https://jsfiddle.net/)
Browser: Chrome v104.0.5112.79, Firefox v91.0.2
Operating System: Windows 11 / macOS Monterey 12.3

Steps to Reproduce:

Open [JSFiddle](https://jsfiddle.net/) in Chrome or Firefox.
Begin writing CSS or JavaScript code in the editor section.
Wait for the autocomplete suggestions to appear.
Observe how the dropdown overlaps with the background content (other code, editor lines).
Expected Result:
The autocomplete dropdown should appear above the code section without overlapping or distorting the content behind it.

Actual Result:
The autocomplete dropdown appears partially or fully behind the code section, making the suggestions hard to see or invisible altogether.

<img width="1440" alt="Screenshot 2024-09-13 at 5 29 11 PM" src="https://github.com/user-attachments/assets/433f36f7-9991-4df4-9c21-14852afa9b54">
<img width="1142" alt="Screenshot 2024-09-13 at 5 45 43 PM" src="https://github.com/user-attachments/assets/7af40c8a-df36-40ec-8f45-872d3203f078">

**Comment by oskarkrawczyk** [comment]
Fixed

**Comment by coolpinkzz** [comment]
Thanks
