### ISSUE TITLE
JSFiddle 3.0 theme is completely broken on Chromebook

### ISSUE THREAD

**Issue by pincesCPU987** [jsfiddle/jsfiddle-users#1887]
Issues: 
 - In dark mode, the editor settings are white text on white background.
 - The text cursor is invisible in both modes
 - The code is uncolored except for defined parameters in JS and defined variables in CSS
 - The yellow accents are either missing or not yellow

Note that this only happens on Chromebook, and the Chromebook does not need to be managed to cause these issues.

Edit: I couldn't add the Bug label to this issue.

**Comment by pincesCPU987** [comment]
The problem has been fixed somehow.

**Comment by oskarkrawczyk** [comment]
@pincesCPU987 Nothing has been done on our end so must have been a problem with your Chrome(book).

**Comment by pincesCPU987** [comment]
There have been many Chromebook issues/bugs lately, so I would not be surprised. Have a nice day!
