### ISSUE TITLE
cant embed jsfiddle

### ISSUE THREAD

**Issue by Joco27** [jsfiddle/jsfiddle-users#1890]
Hi,

I have a simple webpage and I want to embed this: https://jsfiddle.net/b2h59kq7/embedded/ to an iframe(this is just my test fiddle)
Is it possible? I have an old webpage and there my old fiddles are still working...

Thx.

**Comment by Joco27** [comment]
Hi,

Thx for the response! I clicked on embed button, added to html and have this: Refused to display 'https://jsfiddle.net/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by oskarkrawczyk** [comment]
@Joco27 Just tested on a random fiddle, I was able to embed it, in rendered on a 3rd party domain without a problem.

Tested in Safari, Chrome, Firefox.

Do you have a website online I can test your embed and see if I get the same problem?

**Comment by Joco27** [comment]
Not live yet... maybe a server issue! thx

**Comment by oskarkrawczyk** [comment]
Or you're testing on localhost which can cause such issues.
