### ISSUE TITLE
I want to know How to Setting Save URL like HighChart Demo

### ISSUE THREAD

**Issue by nightow** [jsfiddle/jsfiddle-users#1897]
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/floating-false/

or

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/floating-true/

and 

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/legend/layout-horizontal/

etcs.

I want to use it with the URL that consists of these categories.

**Comment by oskarkrawczyk** [comment]
See docs here https://docs.jsfiddle.net/github-integration/untitled-1

**Comment by nightow** [comment]
i`m make repo but 404 error.

https://github.com/ibsheet/ibsheet8/tree/main/samples/withHighChart

https://api.github.com/repos/ibsheet/ibsheet8/contents/samples/withHighChart
has network state 200

The following 4 files (demo.css, demo.details, demo.html, demo.js) were created by referring to the example of highchart.
 
and i connect https://jsfiddle.net/gh/get/library/pure/ibsheet/ibsheet8/tree/main/samples/withHighChart

but 

404
Repository/Gist not found: https://api.github.com/repos/ibsheet/ibsheet8/contents/samples/withHighChart

error message

**Comment by nightow** [comment]
I found the answer to this question.

thx,
