### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by rafal-kepa** [jsfiddle/jsfiddle-users#1898]
Hello,
We had some projects on your platform, avalaible under https://jsfiddle.net/user/Helion_przyklady/fiddles/ address. Unfortunately, this link does not work now, when you click on it, you get HTTP 404 error. 
I can find one particular project - https://jsfiddle.net/Helion_przyklady/ks8c25uf/ (although this link has been also changed, earlier it was https://jsfiddle.net/user/Helion_przyklady/ks8c25uf/), but I can't find a proper link to catalog with all our projects (as I have mentioned, https://jsfiddle.net/user/Helion_przyklady/fiddles/ doesn't work now). 
As far as I know, we haven't made any changes to the files structue. 
Could you help me with this?  It's urgent, this link should be available to our readers.
Best regards,
Rafal Kepa, Helion Publishing House
rafal.kepa@helion.pl

**Comment by oskarkrawczyk** [comment]
@rafal-kepa The URL structure has changed a couple of months ago, fiddles are now available under ` https://jsfiddle.net/u/Helion_przyklady/fiddles/`. If the URLs were printed on paper form, this might be a problem.

**Comment by rafal-kepa** [comment]
Thank you very much for your fast answer.
In fact, this link was printed in our book, but we haven't got any registered problems from readers on that, probably URL structure has changed after our book was sold in paper version, I suppose, that for readers of paper version URL was correct. But we are still selling ebook and PDF version, we should change URL on that for correct one. Thanks to you, we can do it now.

Best regards,
Rafal Kepa, Helion Publishing House
